### ISSUE TITLE
Add more test cases

### ISSUE THREAD

**Issue by Hamsterpants** [thetechcollective/gh-cpissues#32]
### Test cases:
- Correct number of issues copied
- Successful copy of body
- Issue already exist
- No issues with label
- No label found
- Wrong syntax usage

### Source issues:
- Issues to be copied lives in `gh-issues/issues`

**Comment by lakruzz** [comment]
A not on the yaml file (See the workflow https://github-com/thetechcollective/dx-intro)

You need to do something like

```yaml
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  issues:   write   
  repository-projects: write

jobs:
  cpissues:
    name: "Initial commit only"
    runs-on: ubuntu-latest
    run: |
      apt-get update
      apt-get install bats
```

check https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
